// KFutVolei — dados simulados
const TORNEIOS = [
  {
    id: 1,
    nome: "Copa Copacabana Open",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Posto 6 — Praia de Copacabana",
    data: "2025-08-02",
    horario: "08:00",
    inscricao: "R$ 120,00",
    premiacao: "R$ 8.000,00",
    vagas: 32,
    status: "Inscrições abertas",
    organizador: "Arena Futvolei RJ",
    destaque: true
  },
  {
    id: 2,
    nome: "Barra Masters Classic",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1559113513-d5e17e7a24a4?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Barra da Tijuca",
    local: "Praia da Barra — Quiosque Atlântico",
    data: "2025-08-10",
    horario: "09:00",
    inscricao: "R$ 60,00",
    premiacao: "R$ 2.500,00",
    vagas: 24,
    status: "Inscrições abertas",
    organizador: "Barra Futvolei Club",
    destaque: true
  },
  {
    id: 3,
    nome: "Torneio Recreio das Areias",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Recreio dos Bandeirantes",
    local: "Praia do Recreio — Espaço Esportivo",
    data: "2025-08-17",
    horario: "07:30",
    inscricao: "Gratuito",
    premiacao: "Troféus e medalhas",
    vagas: 16,
    status: "Inscrições abertas",
    organizador: "Recreio Esportes",
    destaque: true
  },
  {
    id: 4,
    nome: "Ipanema Beach Pro",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Ipanema",
    local: "Posto 8 — Praia de Ipanema",
    data: "2025-08-24",
    horario: "08:00",
    inscricao: "R$ 150,00",
    premiacao: "R$ 12.000,00",
    vagas: 32,
    status: "Inscrições abertas",
    organizador: "Rio Pro Volei",
    destaque: false
  },
  {
    id: 5,
    nome: "Leblon Cup Verão",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Leblon",
    local: "Praia do Leblon — Arena Sul",
    data: "2025-09-06",
    horario: "09:30",
    inscricao: "R$ 80,00",
    premiacao: "R$ 3.500,00",
    vagas: 20,
    status: "Inscrições abertas",
    organizador: "Leblon Sports",
    destaque: false
  },
  {
    id: 6,
    nome: "Festival Amador Prainha",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1526676037777-05a232554f77?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Prainha",
    local: "Praia da Prainha",
    data: "2025-09-13",
    horario: "07:00",
    inscricao: "Gratuito",
    premiacao: "Kits esportivos",
    vagas: 20,
    status: "Inscrições abertas",
    organizador: "Prainha Surf & Volei",
    destaque: false
  },
  {
    id: 7,
    nome: "Grand Slam Barra Norte",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Barra da Tijuca",
    local: "Praia da Barra Norte — Setor A",
    data: "2025-09-20",
    horario: "08:00",
    inscricao: "R$ 180,00",
    premiacao: "R$ 20.000,00",
    vagas: 48,
    status: "Em breve",
    organizador: "Grand Slam Eventos",
    destaque: false
  },
  {
    id: 8,
    nome: "Circuito Flamengo Beach",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Flamengo",
    local: "Aterro do Flamengo — Arena Central",
    data: "2025-09-27",
    horario: "09:00",
    inscricao: "R$ 50,00",
    premiacao: "R$ 1.800,00",
    vagas: 24,
    status: "Inscrições abertas",
    organizador: "Flamengo Beach Sports",
    destaque: false
  },
  {
    id: 9,
    nome: "Open Amador São Conrado",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1601462904263-f2fa0c851cb9?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "São Conrado",
    local: "Praia de São Conrado",
    data: "2025-10-04",
    horario: "08:00",
    inscricao: "R$ 20,00",
    premiacao: "Medalhas e brindes",
    vagas: 16,
    status: "Inscrições abertas",
    organizador: "São Conrado Esporte Clube",
    destaque: false
  },
  {
    id: 10,
    nome: "Elite Series Copacabana",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1591491558983-a2b3c2f8a0b0?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Posto 4 — Praia de Copacabana",
    data: "2025-10-11",
    horario: "07:30",
    inscricao: "R$ 200,00",
    premiacao: "R$ 15.000,00",
    vagas: 32,
    status: "Inscrições abertas",
    organizador: "Elite Volei Events",
    destaque: false
  },
  {
    id: 11,
    nome: "Torneio Intermediário Grumari",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1548698740-15f2fb8b2ad9?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Grumari",
    local: "Praia de Grumari",
    data: "2025-10-18",
    horario: "08:30",
    inscricao: "R$ 70,00",
    premiacao: "R$ 2.000,00",
    vagas: 20,
    status: "Inscrições abertas",
    organizador: "Oeste Carioca Esportes",
    destaque: false
  },
  {
    id: 12,
    nome: "Copa Família Barra",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1580748142113-18f37e4b0de2?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Barra da Tijuca",
    local: "Barra Beach Club",
    data: "2025-10-25",
    horario: "09:00",
    inscricao: "Gratuito",
    premiacao: "Troféus",
    vagas: 24,
    status: "Em breve",
    organizador: "Barra Família Ativa",
    destaque: false
  },
  {
    id: 13,
    nome: "Pro Tour Ipanema",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1519680050-5d6e1f4be8c8?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Ipanema",
    local: "Quiosque Garota de Ipanema",
    data: "2025-11-01",
    horario: "08:00",
    inscricao: "R$ 160,00",
    premiacao: "R$ 10.000,00",
    vagas: 32,
    status: "Inscrições abertas",
    organizador: "Pro Tour Brasil",
    destaque: false
  },
  {
    id: 14,
    nome: "Desafio Intermediário Leblon",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1561049933-c8fbef47b329?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Leblon",
    local: "Praia do Leblon — Arena Norte",
    data: "2025-11-08",
    horario: "09:00",
    inscricao: "R$ 55,00",
    premiacao: "R$ 2.200,00",
    vagas: 20,
    status: "Inscrições abertas",
    organizador: "Leblon Sports",
    destaque: false
  },
  {
    id: 15,
    nome: "Vidigal Beach Open",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Vidigal",
    local: "Praia do Vidigal",
    data: "2025-11-15",
    horario: "07:30",
    inscricao: "R$ 30,00",
    premiacao: "Medalhas e brindes",
    vagas: 16,
    status: "Inscrições abertas",
    organizador: "Vidigal Esportes",
    destaque: false
  },
  {
    id: 16,
    nome: "Final Series RJ Pro",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Posto 5 — Praia de Copacabana",
    data: "2025-11-22",
    horario: "08:00",
    inscricao: "R$ 220,00",
    premiacao: "R$ 25.000,00",
    vagas: 48,
    status: "Encerrado",
    organizador: "RJ Pro Events",
    destaque: false
  },
  {
    id: 17,
    nome: "Circuito Intermediário Recreio",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Recreio dos Bandeirantes",
    local: "Praia do Recreio — Área Norte",
    data: "2025-11-29",
    horario: "08:30",
    inscricao: "R$ 65,00",
    premiacao: "R$ 1.500,00",
    vagas: 24,
    status: "Inscrições abertas",
    organizador: "Recreio Esportes",
    destaque: false
  },
  {
    id: 18,
    nome: "Summer Open Amador Copacabana",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Posto 2 — Praia de Copacabana",
    data: "2025-12-06",
    horario: "07:00",
    inscricao: "Gratuito",
    premiacao: "Kits e medalhas",
    vagas: 20,
    status: "Em breve",
    organizador: "Summer Carioca",
    destaque: false
  },
  {
    id: 19,
    nome: "Diamond Series Barra",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Barra da Tijuca",
    local: "Praia da Barra — Arena Principal",
    data: "2025-12-13",
    horario: "08:00",
    inscricao: "R$ 250,00",
    premiacao: "R$ 30.000,00",
    vagas: 48,
    status: "Em breve",
    organizador: "Diamond Events",
    destaque: false
  },
  {
    id: 20,
    nome: "Torneio de Verão Intermediário",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Ipanema",
    local: "Posto 9 — Praia de Ipanema",
    data: "2025-12-20",
    horario: "09:00",
    inscricao: "R$ 90,00",
    premiacao: "R$ 4.000,00",
    vagas: 24,
    status: "Em breve",
    organizador: "Verão Carioca Sports",
    destaque: false
  },
  {
    id: 21,
    nome: "Reveillon Amador Leblon",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Leblon",
    local: "Praia do Leblon — Setor 3",
    data: "2025-12-27",
    horario: "07:30",
    inscricao: "R$ 40,00",
    premiacao: "Kits e troféus",
    vagas: 16,
    status: "Em breve",
    organizador: "Leblon Beach Parties",
    destaque: false
  },
  {
    id: 22,
    nome: "Copa Verão Pro Copacabana",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Arena Copacabana — Posto 3",
    data: "2026-01-10",
    horario: "08:00",
    inscricao: "R$ 190,00",
    premiacao: "R$ 18.000,00",
    vagas: 40,
    status: "Em breve",
    organizador: "Copa Verão Eventos",
    destaque: false
  },
  {
    id: 23,
    nome: "Super Liga Intermediária RJ",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Barra da Tijuca",
    local: "Centro Esportivo da Barra",
    data: "2026-01-17",
    horario: "09:00",
    inscricao: "R$ 75,00",
    premiacao: "R$ 3.000,00",
    vagas: 28,
    status: "Em breve",
    organizador: "Super Liga RJ",
    destaque: false
  },
  {
    id: 24,
    nome: "Amador Open Verão Ipanema",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Ipanema",
    local: "Posto 10 — Praia de Ipanema",
    data: "2026-01-24",
    horario: "07:00",
    inscricao: "Gratuito",
    premiacao: "Kits esportivos",
    vagas: 20,
    status: "Em breve",
    organizador: "Ipanema Beach Life",
    destaque: false
  },
  {
    id: 25,
    nome: "Carnival Beach Pro",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Posto 1 — Praia de Copacabana",
    data: "2026-02-14",
    horario: "08:00",
    inscricao: "R$ 210,00",
    premiacao: "R$ 22.000,00",
    vagas: 48,
    status: "Em breve",
    organizador: "Carnival Sports RJ",
    destaque: false
  },
  {
    id: 26,
    nome: "Intermediário Carnaval Barra",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Barra da Tijuca",
    local: "Praia da Barra — Posto 1",
    data: "2026-02-21",
    horario: "09:00",
    inscricao: "R$ 85,00",
    premiacao: "R$ 2.800,00",
    vagas: 24,
    status: "Em breve",
    organizador: "Barra Futvolei Club",
    destaque: false
  },
  {
    id: 27,
    nome: "Festival Amador Recreio Verão",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Recreio dos Bandeirantes",
    local: "Praia do Recreio — Centro",
    data: "2026-02-28",
    horario: "07:30",
    inscricao: "R$ 25,00",
    premiacao: "Medalhas e brindes",
    vagas: 20,
    status: "Em breve",
    organizador: "Recreio Esportes",
    destaque: false
  },
  {
    id: 28,
    nome: "Masters Pro Series Leblon",
    categoria: "Profissional",
    imagem: "https://images.unsplash.com/photo-1504614588353-7f6cd88c28b2?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Leblon",
    local: "Praia do Leblon — Arena Central",
    data: "2026-03-07",
    horario: "08:00",
    inscricao: "R$ 175,00",
    premiacao: "R$ 14.000,00",
    vagas: 32,
    status: "Em breve",
    organizador: "Masters Events",
    destaque: false
  },
  {
    id: 29,
    nome: "Circuito Intermediário São Conrado",
    categoria: "Intermediário",
    imagem: "https://images.unsplash.com/photo-1468818438311-4bab781ab9b8?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "São Conrado",
    local: "Praia de São Conrado — Arena",
    data: "2026-03-14",
    horario: "09:30",
    inscricao: "R$ 60,00",
    premiacao: "R$ 1.800,00",
    vagas: 20,
    status: "Em breve",
    organizador: "São Conrado Esporte Clube",
    destaque: false
  },
  {
    id: 30,
    nome: "Copa Amador Outono Copacabana",
    categoria: "Amador",
    imagem: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    local: "Posto 7 — Praia de Copacabana",
    data: "2026-03-21",
    horario: "08:00",
    inscricao: "Gratuito",
    premiacao: "Troféus e kits",
    vagas: 24,
    status: "Em breve",
    organizador: "Copacabana Sport Club",
    destaque: false
  }
];

const STATS = {
  atletas: 1847,
  torneios: 312,
  cidades: 18,
  inscricoesAbertas: 14
};

const RANKING = [
  { posicao: 1, nome: "Carlos Mendonça", dupla: "Rafael Torres", pontos: 4850, categoria: "Profissional" },
  { posicao: 2, nome: "Bruno Alves", dupla: "Gustavo Lima", pontos: 4620, categoria: "Profissional" },
  { posicao: 3, nome: "Thiago Rocha", dupla: "Anderson Silva", pontos: 4310, categoria: "Profissional" },
  { posicao: 4, nome: "Felipe Cunha", dupla: "Diego Nunes", pontos: 3980, categoria: "Intermediário" },
  { posicao: 5, nome: "Marcos Viana", dupla: "Leandro Costa", pontos: 3720, categoria: "Intermediário" }
];
